print('Hello, World!')
print("Hello World...!! this is my first python program")
print(1 + 2)
print(7 + 6)
print()
print("the end")
print(10/1)
print(10/2)
print(10/3)
print("Keep on watching", " this video ", "to learn more about Python", 3)
